kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    context: src
    dockerfile: src/Dockerfile
    tags: 
      - latest
      - ${DRONE_TAG}
    repo: jjtc/conan_exiles
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
      - master
    event:
      - tag