version: "3.5"

services:
  ce0:
    build: src/
    image: jjtc/conan_exiles:1.4
    restart: unless-stopped
    environment:
      - "CONANEXILES_ServerSettings_ServerSettings_AdminPassword=M@chuP1chu1l1l"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerName=Snnaakeess!!"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerPassword=MySecret"
      - "CONANEXILES_INSTANCENAME=exiles0"
      - "CONANEXILES_Game_RconPlugin_RconEnabled=1"
      - "CONANEXILES_Game_RconPlugin_RconPassword=REDACTED"
      - "CONANEXILES_Game_RconPlugin_RconPort=25575"
      - "CONANEXILES_Game_RconPlugin_RconMaxKarma=60"
    ports:
        - 7777:7777/udp
        - 7778:7778/udp
        - 27015:27015/udp
    volumes:
        - data:/conanexiles

 redis:
    image: redis:5-alpine
    restart: unless-stopped
    environment:
      - "TZ=Europe/Vienna"
    volumes:
      - redis:/data/

volumes:
    data:
    redis:
